api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenObtainPairView
from api.register import RegisterViewSet
from api.cars import CarViewSet
from api.tracks import TrackViewSet
from api.bookings import BookingViewSet, CancelBookingView


router = DefaultRouter()  # instantiate the router
router.register(r'register', RegisterViewSet, basename='register')  # This is the register url
router.register(r'cars', CarViewSet)
router.register(r'tracks', TrackViewSet)
router.register(r'bookings', BookingViewSet)

urlpatterns = [
    path('', include(router.urls)),  # this includes all the urls registered in the router
    path('browser-auth/', include('rest_framework.urls')),
    path('auth/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('bookings/<int:pk>/cancel/', CancelBookingView.as_view(), name='cancel_booking'),

]

bookings/urls.py
from django.urls import path
from bookings.views import show_all_bookings, show_booking_details, create_booking, \
    show_checkout, cancel_booking, remove_car_from_cart, remove_track_from_cart, \
    add_car_to_cart, add_track_to_cart, export_all_bookings


app_name = 'bookings'

urlpatterns = [
    path('', show_all_bookings, name='all'),
    path('create/', create_booking, name='create'),
    path('<int:booking_id>/', show_booking_details, name='details'),
    path('<int:booking_id>/cancel/', cancel_booking, name='cancel_booking'),
    path('checkout/', show_checkout, name='show_checkout'),
    path('<int:car_id>/remove_car_from_cart/', remove_car_from_cart, name='remove_car_from_cart'),
    path('<int:track_id>/remove_track_from_cart/', remove_track_from_cart, name='remove_track_from_cart'),
    path('<int:car_id>/add_car_to_cart/', add_car_to_cart, name='add_car_to_cart'),
    path('<int:track_id>/add_track_to_cart/', add_track_to_cart, name='add_track_to_cart'),
    path('to_csv/', export_all_bookings, name='export_to_csv'),

]

f1experience/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from f1experience.views import homepage_view, search_site, about_page


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('my_admin.urls')),  # my custom admin site
    path('', homepage_view, name='homepage'),
    path('search/', search_site, name='search'),
    path('cars/', include('cars.urls')),
    path('blogs/', include('blogs.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('bookings/', include('bookings.urls')),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),  # just has to be here, for password reset to work properly
    path('about/', about_page, name='about'),
    path('api/', include('api.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bookings/models.py
from django.db import models
from django.conf import settings
import datetime
from cars.models import Car
from tracks.models import Track


class Booking(models.Model):
    booking_number = models.CharField(max_length=9, blank=False, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date = models.DateField(null=True, blank=True)
    cost = models.FloatField(null=True, blank=True, default=0)
    finished = models.BooleanField(default=False)
    canceled = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='bookings')
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='bookings')
    track = models.ForeignKey(Track, on_delete=models.CASCADE, related_name='bookings')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return str(self.booking_number)

    def save(self, *args, **kwargs):
        today = datetime.date.today()
        today_string = today.strftime('%y%m%d')
        next_booking_number = '001'
        last_booking = Booking.objects.order_by('booking_number').last()
        if not self.booking_number:
            if last_booking:
                last_booking_number = int(last_booking.booking_number[6:])
                next_booking_number = '{0:03d}'.format(last_booking_number + 1)
            self.booking_number = today_string + next_booking_number
            super(Booking, self).save(*args, **kwargs)
        else:
            super(Booking, self).save(*args, **kwargs)

    @property
    def status(self):
        status = 'Pending'
        if not self.paid and not self.finished and self.canceled:
            status = 'Canceled'
        elif (not self.paid and not self.finished and not self.canceled) or \
             (self.paid and not self.finished and not self.canceled):
            status = 'Active'
        elif self.paid and self.finished and not self.canceled:
            status = 'Finished'

        return status

    # @property
    # def total_cost(self):
    #     return self.car.rate

    # def human_date(self):
    #     return self.date_created.strftime('%Y-%m-%d %H:%M:%S')
    # human_date.short_description = 'date_created'
    # human_date.admin_order_field = 'date_created'

users/models/details.py
from django.db import models
from django.conf import settings
from django.templatetags.static import static
from django.utils import timezone
from utils.constants.activation import ACTIVATION_DICT


def get_expires_at():
    return timezone.now() + timezone.timedelta(**ACTIVATION_DICT)


class Activation(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='activation')
    token = models.CharField(max_length=64, null=True, default=None, blank=False, unique=True)
    expires_at = models.DateTimeField(default=get_expires_at)
    activated_at = models.DateTimeField(null=True, default=None, blank=False)

    def __str__(self):
        return self.token

    def __repr__(self):
        return self.token


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='profile_images/', null=True, default='users/profile_images/default_image.jpg')

    @property
    def image_url(self):
        if self.avatar:

            return self.avatar.url

        return static('users/profile_images/default_image.jpg')


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart')  # user.cart - gives access to a user's cart
    data = models.JSONField()

bookings/forms.py
from django import forms
from bookings.models import Booking
from tracks.models import TrackAvailableDates
from utils.constants.booking_date_select import AVAILABLE_HOURS, AVAILABLE_MONTHS, \
    AVAILABLE_YEARS, AVAILABLE_DAYS


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        widgets = {
            'user': forms.HiddenInput(),
            'year': forms.Select(choices=AVAILABLE_YEARS),
            'month': forms.Select(choices=AVAILABLE_MONTHS),
            'day': forms.Select(choices=AVAILABLE_DAYS),
            'time': forms.Select(choices=AVAILABLE_HOURS)

        }
        fields = [
            'car',
            'track',
            'year',
            'month',
            'day',
            'time',
        ]


# class BookingDateForm(forms.Form):
#     year = forms.ChoiceField(choices=AVAILABLE_HOURS)
#     month = forms.ChoiceField(choices=(AVAILABLE_HOURS))
#     day = forms.ChoiceField(choices=(AVAILABLE_HOURS))
#     hour = forms.ChoiceField(choices=(AVAILABLE_HOURS))


class BookingDateForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['year', 'month', 'day', 'time', 'user', 'car', 'track' ]
        widgets = {
            'year': forms.Select(choices=AVAILABLE_YEARS),
            'month': forms.Select(choices=AVAILABLE_MONTHS),
            'day': forms.Select(choices=AVAILABLE_DAYS),
            'time': forms.Select(choices=AVAILABLE_HOURS),
            'user': forms.HiddenInput(),
            'car': forms.HiddenInput(),
            'track': forms.HiddenInput(),
        }

    def __init__(self, user, car, track, *args, **kwargs):
        self.user = user
        self.car = car
        self.track = track
        super(BookingDateForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(BookingDateForm, self).save(commit=False)
        instance.user = self.user
        instance.car = self.car
        instance.track = self.track

        if commit:
            instance.save()

        return instance

bookings/views.py
import csv
from django.shortcuts import render, get_object_or_404, redirect, Http404, reverse, HttpResponse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.db.models import Q
from bookings.models import Booking
from utils.cart import Cart
from cars.models import Car
from tracks.models import Track
from utils.constants.booking_limits import CAR_BOOKING_LIMIT


@login_required
def show_all_bookings(request):
    if request.method == 'POST':
        query = request.POST.get('q')
        if query:
            lookups = (Q(car__name__icontains=query) | Q(track__name__icontains=query) | Q(user__email__icontains=query)
                       | Q(track__location__icontains=query) | Q(date_created__year__icontains=query)
                       | Q(date_created__month__icontains=query) | Q(date_created__day__icontains=query)
                       | Q(booking_number__icontains=query))

            bookings = request.user.bookings.filter(lookups).distinct()
            paginator = Paginator(bookings, 15)  # Objects on the page
            page_obj = paginator.get_page(request.GET.get('page', 1))

            return render(request, 'bookings/bookings.html', {
                'page_obj': page_obj,
            })

    bookings = request.user.bookings.all()
    paginator = Paginator(bookings, 15)  # Objects on the page
    page_obj = paginator.get_page(request.GET.get('page', 1))  # sending just one page instead of the whole list

    return render(request, 'bookings/bookings.html', {
        'page_obj': page_obj,
    })


@login_required(login_url='/users/login/')
def show_booking_details(request, booking_id):
    booking = get_object_or_404(Booking, pk=booking_id)

    if booking.user.id != request.user.id:
        raise Http404('Booking not available.')

    return render(request, 'bookings/details.html', {
        'booking': booking,
    })


@login_required(login_url='/users/login/')
def create_booking(request):
    booking = True
    tracks = Track.objects.all()
    paginator = Paginator(tracks, 4)  # Objects on the page
    page_obj = paginator.get_page(request.GET.get('page', 1))

    return render(request, 'tracks/tracks.html', {
        'page_obj': page_obj,
        'booking': booking,
    })


def add_track_to_cart(request, track_id):
    track = get_object_or_404(Track, pk=track_id)
    cart = Cart(request)
    cart.add_track(track_id)
    messages.info(request, f'{track.name} added to your booking.')

    booking = True  # to differentiate between normal view and booking process view
    #  verify car availability
    cars = Car.objects.all()
    available_cars = []
    for car in cars:
        bookings_on_track = Booking.objects.filter(Q(track=track), Q(car=car), Q(canceled=False)).count()
        if bookings_on_track < CAR_BOOKING_LIMIT:
            available_cars.append(car)

    paginator = Paginator(cars, 4)
    page_obj = paginator.get_page(request.GET.get('page', 1))  # Objects on the page

    return render(request, 'cars/cars.html', {
        'page_obj': page_obj,
        'booking': booking,
        'available_cars': available_cars,
    })


def remove_track_from_cart(request, track_id):
    get_object_or_404(Track, pk=track_id)
    cart = Cart(request)
    cart.remove_track()

    messages.success(request, 'Track removed.')

    return redirect(reverse('bookings:show_checkout'))


def add_car_to_cart(request, car_id):
    car = get_object_or_404(Car, pk=car_id)
    cart = Cart(request)
    cart.add_car(car_id)

    messages.info(request, f'{car.name} added to your booking.')

    return redirect(reverse('bookings:show_checkout'))


def remove_car_from_cart(request, car_id):
    get_object_or_404(Car, pk=car_id)
    cart = Cart(request)
    cart.remove_car()

    messages.success(request, 'Car removed.')

    return redirect(reverse('bookings:show_checkout'))


@login_required(login_url='/users/login/')
def show_checkout(request):
    cart = request.session.get('cart', {})  # get cart or create an empty one
    car = Car.objects.filter(id__in=cart.values()).first()
    track = Track.objects.filter(id__in=cart.values()).first()
    user = request.user

    if request.method == 'POST':
        current_booking = Booking(car=car, track=track, user=user, date=track.race_day, cost=car.rate)
        current_booking.save()

        messages.success(request, 'Booking created successfully!')
        request.session['cart'] = {}

        # # Control car availability
        # if car.number_of_bookings >= 5:
        #     car.available = False
        #     car.save()

        return redirect('/')

    return render(request, 'bookings/checkout.html', {
        'car': car,
        'track': track,
    })


@login_required(login_url='/users/login/')
@permission_required('change_booking', raise_exception=False)
def cancel_booking(request, booking_id):
    booking = get_object_or_404(Booking, pk=booking_id)
    booking.canceled = True
    booking.save()

    messages.success(request, 'Booking cancelled successfully!')

    # # Control car availability
    # booking.car.available = True
    # booking.car.save()

    return redirect(reverse('bookings:all'))


@login_required(login_url='/users/login/')
def export_all_bookings(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="my_bookings.csv"'
    bookings = Booking.objects.filter(user=request.user)
    header = ['Booking number', 'Track', 'Car', 'Booked date', 'User email']
    writer = csv.writer(response)
    writer.writerow(header)
    for booking in bookings:
        writer.writerow([booking.booking_number, booking.track, booking.car, booking.date, booking.user])

    return response

bookings/templates/bookings/bookings.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>My bookings</title>
{% endblock %}

{% block content %}

<body style="background-image: url({% static 'cars/images/wallpapers/win.jpg' %})">
    <h2 class="title">My bookings</h2>
    <br>
    {% include 'pagination.html' %}
    <div class="mybookings-container">
        <div class="mybookings-item">
            <a href="{% url 'bookings:export_to_csv' %}" style="text-decoration: none;">
                <button class="long-button" style="margin: 0%;">Export all bookings to csv</button>
            </a>
        </div>
        <div class="mybookings-item">
            <table style="width:60%;">

                <tr>
                    <th>Booking number</th>
                    <th>Track</th>
                    <th>Car</th>
                    <th>Booked date</th>
                    <th>Booking status</th>
                    <th>Details</th>
                </tr>
            {% for booking in page_obj %}
                <tr>
                    <td>{{ booking.booking_number }}</td>
                    <td>{{ booking.track }}</td>
                    <td>{{ booking.car }}</td>
                    <td>{{ booking.date }}</td>
                    <td>{{ booking.status }}</td>
                    <td>
                        <a href="{% url 'bookings:details' booking.id %}" style="text-decoration: none;">
                            <button class="long-button" style="width: 150px;">Order details</button>
                        </a>
                    </td>

                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
</body>


{% endblock %}

bookings/templates/bookings/checkout.html
{% extends 'base.html' %}

{% block title %}
    <title>Checkout</title>
{% endblock %}

{% block content %}
<div class="title">
    <h2>Booking details</h2>
</div>
<br>
    <div class="checkout-container">
        {% if not car and not track %}
            <h4>No booking in progress.</h4>
        {% else %}
            {% if track %}
                <div class="checkout-item">
                    {% for image in track.first_image_url %}
                        <img src="{{ image }}" alt="" height="180px">
                    {% endfor %}
                    <br>
                    <p><strong>Selected track: </strong>{{ track.name }} - {{ track.location }}</p>
                        <form method="post" action="{% url 'bookings:remove_track_from_cart' track.id %}">
                            {% csrf_token %}
                            <input class="long-button red-button" type="submit" value="Remove"/>
                        </form>
                </div>
            {% endif %}

            {% if car %}
                <div class="checkout-item" style="display: flex; justify-content: space-between; padding-top: 80px;">
                    {% for image in car.image_urls %}
                        <img src="{{ image }}" alt="car_image" height="100px">
                    {% endfor %}
                    <p><strong>Selected car: </strong>{{ car.name }}</p>
                    <br>
                    <form method="post" action="{% url 'bookings:remove_car_from_cart' car.id %}">
                        {% csrf_token %}
                        <input class="long-button red-button" type="submit" value="Remove"/>
                    </form>
                </div>

            {% endif %}
            <div class="checkout-item">
                {% if car %}
                    <p><strong>Total cost: </strong>{{ car.rate }} EUR/session</p>
                {% endif %}

                {% if track %}
                    <p><strong>Booking date: </strong>{{ track.race_day }}</p>
                {% endif %}
            </div>            
        {% endif %}
    </div>
    <br>
    {% if car and track %}
        <div style="display: flex; justify-content: center;">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="lights-on" style="height: 70px; width: 350px; font-size: 17px;">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    Confirm booking
                </button>
            </form>
        </div>
    {% endif %}
{% endblock %}

bookings/templates/bookings/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Booking details</title>
{% endblock %}

{% block content %}

<body style="background-image: url({% static 'cars/images/wallpapers/win.jpg' %})">
    <h2 class="title">Booking details</h2>
    <br>
    <div class="checkout-item" style="background-color: rgba(255, 255, 255, 0.658);">

        <div style="width: auto; align-items:  left;">
            <p><strong>Booking number: {{ booking.booking_number }}</strong></p>
            <p>Status: {{ booking.status }}</p>
            <p>Name: {{ booking.user.first_name }} {{ booking.user.last_name }}</p>
            <p>Date and time reserved: {{ booking.date }}</p>
            <p>Total cost: {{ booking.cost }} EUR</p>
        </div>
        <div style="width: auto;">
            {% for image in booking.car.image_urls %}
                <img src="{{ image }}" alt="" width="400px">
            {% endfor %}
            <p>Car: {{ booking.car }}</p>
        </div>
        <div style="width: auto;">
            {% for image in booking.track.first_image_url %}
                <img src="{{ image }}" alt="" height="250px">
            {% endfor %}
            <p>Circuit: {{ booking.track }}</p>
        </div>
        <div>
            {% if not booking.canceled %}
            <form method="post" action="{% url 'bookings:cancel_booking' booking.id %}">
                {% csrf_token %}
                <input class="long-button red-button" type="submit" value="Cancel booking"/>
            </form>
            {% endif %}
        </div>
    </div>
</body>

{% endblock %}

bookings/templates/bookings/search_bookings.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>My bookings</title>
{% endblock %}

{% block content %}
<div style="color: white">
    <body style="background-image: url(//localhost:8000/static/cars/images/wallpapers/win.jpg)">
    <h2 style="color: white">My bookings</h2>
         <div class="pagination">
            {% if page_obj.paginator.num_pages > 1 %}
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            {% endif %}
        </div>
        <div style="color: white">
            {% for booking in page_obj %}
                <ul>
                    <li style="background: black" >
                        {{ booking.booking_number }} - {{ booking.track }} - {{ booking.car }} - {{ booking.date }} - {{ booking.status }}
                        <a href="{% url 'bookings:details' booking.id %}">Order details</a>
                    </li>
                </ul>

            {% endfor %}
        </div>
    </body>
</div>

{% endblock %}