api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenObtainPairView
from api.register import RegisterViewSet
from api.cars import CarViewSet
from api.tracks import TrackViewSet
from api.bookings import BookingViewSet, CancelBookingView


router = DefaultRouter()  # instantiate the router
router.register(r'register', RegisterViewSet, basename='register')  # This is the register url
router.register(r'cars', CarViewSet)
router.register(r'tracks', TrackViewSet)
router.register(r'bookings', BookingViewSet)

urlpatterns = [
    path('', include(router.urls)),  # this includes all the urls registered in the router
    path('browser-auth/', include('rest_framework.urls')),
    path('auth/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('bookings/<int:pk>/cancel/', CancelBookingView.as_view(), name='cancel_booking'),

]

blogs/urls.py
from django.urls import path
from blogs.views import PostList, PostCreateView, PostUpdateView, PostDeleteView, post_detail
from blogs.feeds import LatestPostsFeed


app_name = 'blogs'

urlpatterns = [
    path('', PostList.as_view(), name='all'),
    path('create/', PostCreateView.as_view(), name='create'),  # this must be before 'details'
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', PostDeleteView.as_view(), name='delete'),
    path('<slug:slug>/', post_detail, name='post_detail'),
    path('feed/rss/', LatestPostsFeed(), name='post_feed'),

]

f1experience/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from f1experience.views import homepage_view, search_site, about_page


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('my_admin.urls')),  # my custom admin site
    path('', homepage_view, name='homepage'),
    path('search/', search_site, name='search'),
    path('cars/', include('cars.urls')),
    path('blogs/', include('blogs.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('bookings/', include('bookings.urls')),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),  # just has to be here, for password reset to work properly
    path('about/', about_page, name='about'),
    path('api/', include('api.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


AuthUserModel = get_user_model()

STATUS = (
    (0, 'Draft'),
    (1, 'Publish')
)


class Post(models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    author = models.ForeignKey(AuthUserModel, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:post_detail', kwargs={'slug': str(self.slug)})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blogs/forms.py
from django import forms
from blogs.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'status']
        widgets = {
            'title': forms.TextInput(attrs={'size': '100'}),
            'content': forms.Textarea(attrs={'cols': '145'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blogs/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.shortcuts import get_object_or_404, render
from blogs.models import Post, Comment
from blogs.forms import PostForm, CommentForm


class PostList(ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_at')
    template_name = 'blogs/post_list.html'


class PostDetails(DetailView):
    model = Post
    template_name = 'blogs/post_detail.html'


class PostCreateView(CreateView):
    form_class = PostForm
    model = Post
    template_name = 'blogs/post_create_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content', ]
    template_name = 'blogs/post_update.html'


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blogs/post_confirm_delete.html'
    success_url = reverse_lazy('blogs:all')  # We have to use reverse_lazy() instead of reverse(), as the urls are not loaded when the file is imported.


def post_detail(request, slug):
    template_name = 'blogs/post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create object but don't save it to the db yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
         comment_form = CommentForm()

    return render(request, template_name, {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
    })

blogs/templates/blogs/post_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Delete post@MoonlitFarm</title>
{% endblock %}

{% block content %}

<div class="main">
    <div class="container">
        <h4 align="center">Deleting post</h4>
    </div>
</div>
<br>

<div align="center">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object.title }}"?</p>
        <button class="btn btn-danger" type="submit">Confirm</button>
    </form>
</div>

{% endblock %}

blogs/templates/blogs/post_create_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>New post@MoonlitFarm</title>
{% endblock %}

{% block content %}

<div class="main">
    <div class="container">
        <h4 align="center">Creating a new post</h4>
    </div>
</div>
<br>


<div class="col-md-8 mt-3 left">
    <div class="card mb-4">
        <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
        </div>
    </div>

</div>

{% endblock %}

blogs/templates/blogs/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Blogs: {{ post.title }}</title>
{% endblock %}

{% block content %}
<div class="main">
    <div class="container">
        <div class="row">
            <div class="col-md-8 card mb-4  mt-3 left  top">
                <div class="card-body">
                    <h4>{{ post.title }}</h4>
                    <p class="text-muted">{{ post.author }} | {{ post.created_at }}</p>
                    <p class="card-text">{{ post.content }}</p>
                        {% if request.user.is_superuser or request.user == post.author %}
                            <a href="{% url 'blogs:update' post.slug  %}" class="long-button">Update post</a>
                            <a href="{% url 'blogs:delete' post.slug  %}" class="long-button red-button">Delete post</a>
                        {% endif %}
                </div>
            </div>
                    {% block sidebar %} {% include 'blogs/sidebar.html' %} {% endblock sidebar %}
            <div class="col-md-8 card mb-4  mt-3 ">
                <div class="card-body">
                    <!-- comments -->
                    <h5>{{ comments.count }} comments</h5>

                    {% for comment in comments %}
                        <div class="comments" style="padding: 10px;">
                            <p class="font-weight-bold">
                                {{ comment.name }}
                                <span class=" text-muted font-weight-normal">
                                    {{ comment.created_on }}
                                </span>
                            </p>
                            {{ comment.body | linebreaks }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-8 card mb-4  mt-3 ">
                <div class="card-body">
                    {% if new_comment %}
                        <div class="alert alert-success" role="alert">
                            Your comment is awaiting moderation.
                        </div>
                    {% else %}
                        <h3>Leave a comment</h3>
                        <form method="post" style="margin-top: 1.3em;">
                            {{ comment_form | crispy }}
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    {% endif %}
                </div>
            </div>

        </div>

    </div>
</div>

{% endblock %}

blogs/templates/blogs/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Blogs</title>
{% endblock %}

{% block content %}

<header class="masthead">
    <h2 class="title">Welcome to our blog</h2>
</header>
<div class="container">
    <a href="{% url 'blogs:create' %}" class="btn btn-primary">New Post</a>
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_at }} </p>
                    <p class="card-text">{{ post.content|slice:":200" }}</p>
                    <div class="container">
                        <a href="{% url 'blogs:post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                        {% if request.user.is_superuser or request.user == post.author %}
                            <a href="{% url 'blogs:update' post.slug  %}" class="btn btn-success">Update post</a>
                            <a href="{% url 'blogs:delete' post.slug  %}" class="btn btn-danger">Delete post</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}

blogs/templates/blogs/post_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Update post@MoonlitFarm</title>
{% endblock %}

{% block content %}

<div class="main">
    <div class="container">
        <h4 align="center">Updating post << {{ post.title }} >></h4>
    </div>
</div>
<br>

<div class="col-md-8 mt-3 left">
    <div class="card mb-4">
        <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
        </div>
    </div>

</div>

{% endblock %}

blogs/templates/blogs/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
    <div class="card my-4">
            <h5 class="card-header">About the author</h5>
        <div class="card-body">
            <img src="{{ post.author.profile.image_url }}" width="300px"  alt="profile image">
            <p class="card-text">{{ post.author }}</p>
            <p class="card-text">Stuff about me</p>
            <a href="#"
               class="btn btn-danger">Contact me</a>
        </div>
    </div>
</div>

{% endblock sidebar %}