api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenObtainPairView
from api.register import RegisterViewSet
from api.cars import CarViewSet
from api.tracks import TrackViewSet
from api.bookings import BookingViewSet, CancelBookingView


router = DefaultRouter()  # instantiate the router
router.register(r'register', RegisterViewSet, basename='register')  # This is the register url
router.register(r'cars', CarViewSet)
router.register(r'tracks', TrackViewSet)
router.register(r'bookings', BookingViewSet)

urlpatterns = [
    path('', include(router.urls)),  # this includes all the urls registered in the router
    path('browser-auth/', include('rest_framework.urls')),
    path('auth/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('bookings/<int:pk>/cancel/', CancelBookingView.as_view(), name='cancel_booking'),

]

bookings/urls.py
from django.urls import path
from bookings.views import show_all_bookings, show_booking_details, create_booking, \
    show_checkout, cancel_booking, remove_car_from_cart, remove_track_from_cart, \
    add_car_to_cart, add_track_to_cart, export_all_bookings


app_name = 'bookings'

urlpatterns = [
    path('', show_all_bookings, name='all'),
    path('create/', create_booking, name='create'),
    path('<int:booking_id>/', show_booking_details, name='details'),
    path('<int:booking_id>/cancel/', cancel_booking, name='cancel_booking'),
    path('checkout/', show_checkout, name='show_checkout'),
    path('<int:car_id>/remove_car_from_cart/', remove_car_from_cart, name='remove_car_from_cart'),
    path('<int:track_id>/remove_track_from_cart/', remove_track_from_cart, name='remove_track_from_cart'),
    path('<int:car_id>/add_car_to_cart/', add_car_to_cart, name='add_car_to_cart'),
    path('<int:track_id>/add_track_to_cart/', add_track_to_cart, name='add_track_to_cart'),
    path('to_csv/', export_all_bookings, name='export_to_csv'),

]

cars/urls.py
from django.urls import path
from cars.views import show_all_cars, show_car_details

app_name = 'cars'

urlpatterns = [
    path('', show_all_cars, name='all'),
    path('<int:car_id>/', show_car_details, name='details'),

]

f1experience/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from f1experience.views import homepage_view, search_site, about_page


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('my_admin.urls')),  # my custom admin site
    path('', homepage_view, name='homepage'),
    path('search/', search_site, name='search'),
    path('cars/', include('cars.urls')),
    path('blogs/', include('blogs.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('bookings/', include('bookings.urls')),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),  # just has to be here, for password reset to work properly
    path('about/', about_page, name='about'),
    path('api/', include('api.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cars/models.py
from django.db import models
from django.utils.text import slugify
from django.templatetags.static import static
from django.conf import settings
import json
from django.db.models import Q


# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name_plural = 'categories'

    name = models.CharField(max_length=128, null=False)

    def __str__(self):
        return self.name


class Car(models.Model):
    name = models.CharField(max_length=128, unique=True, null=False)
    power_unit = models.CharField(max_length=64, unique=False, null=False)
    races_won = models.IntegerField(default=0)
    handling = models.CharField(max_length=128, null=False)
    rate = models.IntegerField(default=1000)
    available = models.BooleanField(default=True)
    color = models.CharField(max_length=24, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL,
                                 related_name='cars', null=True, default=None)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              related_name='cars', null=True, default=None)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['name']

    @property
    def image_urls(self):
        slug = slugify(self.name)

        return [static(f'cars/images/small/{slug}.png')]

    @property
    def gallery_image_urls(self):
        with open('cars/fixtures/car-gallery-images.json') as jsonfile:
            jsonobj = json.load(jsonfile)

        gallery = jsonobj[self.name]
        image_urls = []

        for image in gallery:
            image_urls += [static(image)]

        return image_urls

    @property
    def number_of_bookings(self):
        bookings = Car.objects.filter(bookings__car=self).count()

        return bookings

    @property
    def number_of_active_bookings(self):
        bookings = Car.objects.filter(Q(bookings__car=self), Q(bookings__canceled=False)).count()

        return bookings

    # @property
    # def get_last_booking(self):
    #     latest_booking = Booking.objects.filter(car=self).order_by('-date').first()
    #
    #     return latest_booking

users/models/details.py
from django.db import models
from django.conf import settings
from django.templatetags.static import static
from django.utils import timezone
from utils.constants.activation import ACTIVATION_DICT


def get_expires_at():
    return timezone.now() + timezone.timedelta(**ACTIVATION_DICT)


class Activation(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='activation')
    token = models.CharField(max_length=64, null=True, default=None, blank=False, unique=True)
    expires_at = models.DateTimeField(default=get_expires_at)
    activated_at = models.DateTimeField(null=True, default=None, blank=False)

    def __str__(self):
        return self.token

    def __repr__(self):
        return self.token


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='profile_images/', null=True, default='users/profile_images/default_image.jpg')

    @property
    def image_url(self):
        if self.avatar:

            return self.avatar.url

        return static('users/profile_images/default_image.jpg')


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart')  # user.cart - gives access to a user's cart
    data = models.JSONField()

cars/forms.py
from django import forms
from cars.models import Category, Car


ORDER_BY_CHOICES = (('POPULARITY', 'Popularity'), ('PRICE_ASC', 'Price ascending'), ('PRICE_DESC', 'Price descending'))


def get_orderby_field(order_by):
    if order_by == 'PRICE_ASC':
        return 'rate'

    if order_by == 'PRICE_DESC':
        return '-rate'

    if order_by == 'POPULARITY':

        return 'id'

    return 'id'


class FilterCarsForm(forms.Form):
    order_by = forms.ChoiceField(choices=ORDER_BY_CHOICES, required=False)
    powered_by = forms.MultipleChoiceField(choices=(), widget=forms.CheckboxSelectMultiple, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        categories = Category.objects.all()
        self.fields['powered_by'].choices = tuple((category.id, category.name) for category in categories)

    def clean_categories(self):
        categories = self.cleaned_data.get('powered_by', [])
        return categories

    def apply_filters(self):
        is_valid = self.is_valid()
        if is_valid:
            order_by = get_orderby_field(self.cleaned_data.get('order_by'))
            categories = self.cleaned_data.get('powered_by', [])

            cars = Car.objects.order_by(order_by)

            if len(categories) > 0:
                cars = cars.filter(category__id__in=categories)

            return cars

        return Car.objects.all()

cars/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.core.paginator import Paginator
from cars.models import Car
from cars.forms import FilterCarsForm


def show_all_cars(request):
    form = FilterCarsForm(request.GET)
    form.is_valid()
    cars = form.apply_filters()

    paginator = Paginator(cars, 4)
    page_obj = paginator.get_page(request.GET.get('page', 1))  # Objects on the page

    return render(request, 'cars/cars.html', {
        'page_obj': page_obj,  # sending just one page instead of the whole list
        'form': form,
    })


def show_car_details(request, car_id):
    car = get_object_or_404(Car, pk=car_id)

    return render(request, 'cars/details.html', {
        'car': car,
    })

cars/templates/cars/car_gallery.html
<!-- Container for the image gallery -->
<div class="new-container">
    <!-- Full-width images with number text -->
    {% for image in car.gallery_image_urls %}
        <div class="mySlides">        
            <img src="{{ image }}" style="width: 1000px; height: 600px; ">
        </div>
    {% endfor %}

    <!-- Next and previous buttons -->
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

    <!-- Image text -->
    <!-- <div class="caption-container">
        <p id="caption">{{ image.name }}</p>
    </div> -->

    <!-- Thumbnail images -->


</div>

cars/templates/cars/cars.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    <title>F1 experience</title>
{% endblock %}

{% block content %}
<div>
    <h2 class="title">Constructors list:</h2>
    <br>
    {% include 'pagination.html' %}
</div>
<div class="cars-container">
    <div class="cars-content">


        <div class="cars-list">
            {% for car in page_obj %}
            <div class="cars-item">
                <div>
                    {% for image in car.image_urls %}
                        {% if booking %}
                            <img src="{{ image }}" alt="Car image" width="432px">
                        {% else %}
                            <a href="{% url 'cars:details' car.id %}">
                                <img src="{{ image }}" alt="Car details" width="432px">
                            </a>
                        {% endif %}
                    {% endfor %}
                </div>
                <br>
                <div>
                    <p style="text-align: center; align-content: center;">
                        Team: <strong>{{ car.name }}</strong>
                        Power unit: <strong> {{ car.power_unit }}</strong>
                        Handling: <strong>{{ car.handling }}/10</strong>
                        <br>
                        Rate: {{ car.rate }} EUR per session
                    </p>
                    <div style="display: flex; justify-content: center;">
                        {% if booking %}
                            {% if car in available_cars %}
                                <a href="{% url 'bookings:add_car_to_cart' car.id %}" style="text-decoration: none;">
                                    <button class="lights-on">
                                        <span></span>
                                        <span></span>
                                        <span></span>
                                        <span></span>
                                        Book this car
                                    </button>
                                </a>
                            {% else %}
                                <a href="" style=" text-decoration: none;">
                                    <button class="long-button btn-warning" style="cursor: not-allowed;" disabled>Fully booked!
                                    </button>
                                </a>
                            {% endif %}
                        {% else %}
                            <a href="{% url 'cars:details' car.id %}" style="text-decoration: none;">
                                <button class="long-button">More details</button>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% if not booking %}
    <div class="card cars-filters">
        <div class="card-body">
            <form method="get" action="{% url 'cars:all' %}">
                {{ form.as_p}}
                <input type="submit" value="Apply filters" class="btn btn-info" style="display: block; margin: 5px auto; padding: 1px 70px;"/>
            </form>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

cars/templates/cars/details.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ car.name }}</title>
{% endblock %}

{% block content %}
<div>
    <h3 class="title">{{ car.name }}</h3>
    <br>
    <button class="long-button" style="padding: 1px 20px;">
        <a href="{% url 'cars:all' %}" style=" text-decoration: none; color: white;">Back to list view</a>
    </button>
</div>
<div class="cars-details">

    <div class="cars-content">
        {% include 'cars/car_gallery.html' %}
    </div>
    <div class="card cars-description">
        <div class="card-body">
            <p><strong>Category:</strong> {{ car.category.name }}</p>
            <p><strong>Team name:</strong> {{ car.name }}</p>
            <p><strong>Power unit:</strong> {{ car.power_unit }}</p>
            <p><strong>Handling: </strong>{{ car.handling }}/10</p>
            <p><strong>Rate:</strong> {{ car.rate }} EUR per session</p>
            {% if request.user.is_authenticated %}
                <p>Times booked so far: {{ car.bookings.all.count }}</p>
            {% endif %}
        </div>
    </div>

</div>
{% endblock %}