api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenObtainPairView
from api.register import RegisterViewSet
from api.cars import CarViewSet
from api.tracks import TrackViewSet
from api.bookings import BookingViewSet, CancelBookingView


router = DefaultRouter()  # instantiate the router
router.register(r'register', RegisterViewSet, basename='register')  # This is the register url
router.register(r'cars', CarViewSet)
router.register(r'tracks', TrackViewSet)
router.register(r'bookings', BookingViewSet)

urlpatterns = [
    path('', include(router.urls)),  # this includes all the urls registered in the router
    path('browser-auth/', include('rest_framework.urls')),
    path('auth/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('bookings/<int:pk>/cancel/', CancelBookingView.as_view(), name='cancel_booking'),

]

blogs/urls.py
from django.urls import path
from blogs.views import PostList, PostCreateView, PostUpdateView, PostDeleteView, post_detail
from blogs.feeds import LatestPostsFeed


app_name = 'blogs'

urlpatterns = [
    path('', PostList.as_view(), name='all'),
    path('create/', PostCreateView.as_view(), name='create'),  # this must be before 'details'
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', PostDeleteView.as_view(), name='delete'),
    path('<slug:slug>/', post_detail, name='post_detail'),
    path('feed/rss/', LatestPostsFeed(), name='post_feed'),

]

cars/urls.py
from django.urls import path
from cars.views import show_all_cars, show_car_details

app_name = 'cars'

urlpatterns = [
    path('', show_all_cars, name='all'),
    path('<int:car_id>/', show_car_details, name='details'),

]

f1experience/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from f1experience.views import homepage_view, search_site, about_page


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('my_admin.urls')),  # my custom admin site
    path('', homepage_view, name='homepage'),
    path('search/', search_site, name='search'),
    path('cars/', include('cars.urls')),
    path('blogs/', include('blogs.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('bookings/', include('bookings.urls')),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),  # just has to be here, for password reset to work properly
    path('about/', about_page, name='about'),
    path('api/', include('api.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracks/urls.py
from django.urls import path
from tracks.views import show_all_tracks, show_track_details


app_name = 'tracks'

urlpatterns = [
    path('', show_all_tracks, name='all'),
    path('<int:track_id>/', show_track_details, name='details'),  # 'details' is the name of the link, to be used in html

]

users/urls.py
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from users.views import login_user, register_user, logout_user, show_profile, activate, regenerate_token, password_reset_request

app_name = 'users'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register_user, name='register'),
    path('profile/', show_profile, name='profile'),
    path('activate/<str:token>/', activate, name='activate'),
    path('regenerate_token/<str:token>/', regenerate_token, name='regenerate_token'),
    path('password_reset/', password_reset_request, name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('social_auth/', include('social_django.urls')),
]

templates/Untitled-3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        .grow {
            padding: 5px 5px 5px 5px;
            border-radius:10px;
                height: 50px; 
                width: 22%; 
                margin: 5px 1% 5px 1%; 
                float: left; 
                position: relative; 
                transition:height 0.5s; 
                -webkit-transition:height 0.5s; 
                text-align: center;

        }
        .grow:hover {
            height: 115px; /* This is the height on hover */
        }

    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <div class="grow" style="background-color: #2a75a9;">
        <h2>Title</h2> <br>
        Contrary to popular belief, Lorem Ipsum is not simply random text.  It has roots in a piece of classical Latin literature
    </div>
</body>
</html>

templates/about_us.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
<head>
    <title>F1 experience</title>

</head>
{% endblock %}

{% block content %}
<div class="main">
  <div class="about-section">
    <h1>About Us Page</h1>
    <p>Some text about who we are and what we do.</p>
  </div>

  <h2 style="text-align:center">Our Team</h2>
  <div class="row">
    <div class="column" style="align:center">
      <div class="aboutpage-card">
        <img src="{% static 'images/Moi2.jpg' %}" alt="Alex" style="width:100%">
        <div class="container">
          <h2>Alex Florea</h2>
          <p class="title">CEO & Founder</p>
          <p>Some text that describes me best. Soon.</p>
          <p>alexandru.floreaf1@gmail.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
    <div class="column" style="align:center">
      <div class="aboutpage-card">
        <img src="{% static 'images/Rockjaw.jpg' %}" alt="Rockjaw" style="width:100%">
        <div class="container">
          <h2>Rock Jaw</h2>
          <p class="title">Master at Arms</p>
          <p>Soon...</p>
          <p>yanevagonnacatchme@gmail.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
    <div class="column" style="align:center">
      <div class="aboutpage-card">
        <img src="{% static 'images/SirB.jpg' %}" alt="SirB" style="width:100%">
        <div class="container">
          <h2>Sir Bartolomei Steal-a-lot</h2>
          <p class="title">Chief Director</p>
          <p>All your treats are belong to us!!!</p>
          <p>yanevagonnacatchmeeither@gmail.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/base.html
<html>
    <head>
        {% load static %}

        {% block title %}
        {% endblock %}

        {% block styles %}
            <link rel="stylesheet" href="{% static 'styles/main.css' %}">
            <link rel="stylesheet" href="{% static 'styles/menu.css' %}">
            <link rel="stylesheet" href="{% static 'styles/base.css' %}">
            <link rel="stylesheet" href="{% static 'cars/styles/car_gallery.css' %}">
            <link rel="stylesheet" href="{% static 'styles/about_page.css' %}">
            <link rel="stylesheet" href="{% static 'tracks/styles/tracks.css' %}">
            <link rel="stylesheet" href="{% static 'cars/styles/cars.css' %}">
            <link rel="stylesheet" href="{% static 'bookings/styles/bookings.css' %}">
            <link rel="stylesheet" href="{% static 'users/styles/profile.css' %}">
            <!-- Load icon library -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <link rel="icon" type="image/x-icon" href="{% static 'cars/images/logos/F1-logo-red.png' %}">
            <link rel="icon" type="image/x-icon" href="{% static 'cars/images/logos/favicon.ico' %}">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% endblock %}
        {% block script %}
            <script src="{% static 'cars/js/car_gallery.js' %}"></script>
            <script src="{% static 'cars/js/msg_delay.js' %}"></script>
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        {% endblock %}
    </head>
    <body>
        <div style=" min-height: calc(100vh - 165px)!important;">
            {% include 'messages.html' %}
            {% include 'menu.html' %}

            {% block content %}

            {% endblock %}
        </div>
        <footer>
            <p>Formula 1 Experience</p>
            <a href="{% url 'about' %}">About us</a>
        </footer>
    </body>

</html>

templates/homepage copy.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
<head>
    <title>F1 experience</title>
</head>
{% endblock %}

{% block content %}
<body style="background-image: url(/static/cars/images/wallpapers/win.jpg);">
    <div class="main">
        <h2>
            <img src="{% static 'cars/images/logos/F1-logo-red.png' %}" width="75px"  alt=""/>
            <span>{{ title }}</span>
        </h2>
        <div class="hp-container">
            <div class="side-card">
                <h4>Most wanted:</h4>
                <ul>
                    {% for key, value in top_5.items %}
                        <li style="margin-bottom: 0px;">
                            <strong>{{ key }}</strong>: {{ value }} rentals
                        </li>
                    {% endfor %}
                </ul>
            </div>  
            <div>
                <h5>Latest bookings</h5>
                <ul>
                    {% for booking in latest_bookings %}
                        <li>
                            {{ booking.booking_number }} - {{ booking.car }} - {{ booking.track }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div>
            {% block random_fact %}
                {% autoescape on %}
                <p><strong>Random F1 fact:</strong> {{ random_fact }}</p>
                {% endautoescape %}
            {% endblock random_fact %}
            </div>
            <div>
                <h5>Wanna see what it's like for an amateur to drive an F1 car?</h5>
                <iframe width="650" height="350" src="https://www.youtube.com/embed/kEP9R-osh7o" title="YouTube video player" frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</body>

{% endblock %}

templates/homepage.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
<head>
    <title>F1 experience</title>
</head>
{% endblock %}

{% block content %}

    <div class="hp-container">
        <span>
            <img src="/static/cars/images/wallpapers/win.jpg" alt="" style="width: 100vw;">
        </span>
        <div class="hp-title-container">
            <div class="hp-title">
                <h2 style="font-size: 4em; font-weight: 700;">
                    <img src="{% static 'cars/images/logos/F1-logo-red.png' %}" width="150px"  alt=""/>
                    <span>{{ title }}</span>        
                </h2>
            </div>
            <div style="position: absolute; top: 200px; left: 45%;">
                <a href="{% url 'bookings:create' %}" style="text-decoration: none;">
                    <button class="lights-on" style="height: 65px;">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        Starts right here!
                    </button>
                </a>
            </div>
        </div>
        <div class="hpcard-holder">
            <div class="hp-card">
                <h4>Most wanted:</h4>
                <ul>
                    {% for key, value in top_5.items %}
                        <li style="margin-bottom: 0px;">
                            <strong>{{ key }}</strong>: {{ value }} rentals
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="hp-card">

            <h5>Sneak peak into the action</h5>
            <iframe width="550" height="350" src="https://www.youtube.com/embed/kEP9R-osh7o" title="YouTube video player" frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="hp-card">
                {% block random_fact %}
                {% autoescape on %}
                <h5>Random F1 fact:</h5>
                {{ random_fact }}
                {% endautoescape %}
            {% endblock random_fact %}
            </div>
        </div>
    </div>


{% endblock %}

templates/menu.html
{% load static %}
{% load cart %}

<div class="topnav">
    
        <div>
            <a href="/">Homepage</a>
            <a href="{% url 'cars:all' %}">Teams</a>
            <a href="{% url 'tracks:all' %}">Tracks</a>
            <a href="{% url 'blogs:all' %}">Blogs</a>
            <a href="{% url 'bookings:create' %}" style="color: rgb(241, 1, 1);"><strong>Start booking process</strong></a>
        </div>

        <form class="search" method="POST" action="{% url 'search' %}" style="width: 500px;">
            <input type="text" name="q" value="{{request.POST.q}}" placeholder="Search for cars, tracks, bookings, dates..." required />
            <button type="submit"><i class="fa fa-search"></i></button>

            {% csrf_token %}
        </form>
    

        <div class="topnav-right">
            {% if request.user.is_authenticated %}
                {% cart_link request.session %}

                <div class="dropdown">
                    <button class="dropbtn">Welcome, {{ user.first_name }}! <img src="{{ request.user.profile.image_url }}" width="20px"  alt="profile image"></button>
                    <div class="dropdown-content">
                        <a href="{% url 'bookings:all' %}">My bookings</a>
                        <a href="{% url 'users:profile' %}">My profile</a>
                        {% if request.user.is_superuser or request.user.is_staff %}
                            <a href="{% url 'admin:index' %}">Admin</a>
                        {% endif %}
                        <a href="{% url 'users:logout' %}">Logout</a>
                    </div>
                </div>

            {% else %}
                <a href="{% url 'users:login' %}">Login</a>
                <a href="{% url 'users:register' %}">Register</a>
                <a href="{% url 'users:password_reset' %}">Forgot password?</a>
            {% endif %}
        </div>

</div>

templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div id="msg" class="container-fluid p-0" style="position: absolute; top: 56px; z-index: 1000;">
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">X</span>
            </button>
        {{ message }}
        </div>
    </div>
    {% endfor %}
{% endif %}

templates/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.paginator.num_pages > 1 %}
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                {% endif %}
                    <li class="page-item disabled"><a class="page-link" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
                {% endif %}
        {% endif %}
    </ul>
</nav>

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Search results</title>
{% endblock %}

{% block content %}
<body style="background-image: url({% static 'cars/images/wallpapers/win.jpg' %}); background-attachment: fixed;">

<!--        <div>-->
        <h2 class="title">Search results:</h2>
        <br>
<!--        </div>-->
    <div style="display: flex;flex-direction: column;">
        <div class="search-container">
            {% if not cars and not tracks and not bookings %}
            <div class="search-item">
                <h5>No results for "{{ query }}"</h5>
            </div>
            {% endif %}
            
            <!-- Cars results -->
            {% if cars %}
            <div class="search-item">
                <h5>Results for "{{ query }}" in Cars</h5>
                {% for car in cars %}
                    <ul>
                        <li>
                            {{ car.name }}
                            {% for image in car.image_urls %}
                                <a href="{% url 'cars:details' car.id %}">
                                    <img src="{{ image }}" alt="Car details" width="200px">
                                </a>
                            {% endfor %}
                            <a href="{% url 'cars:details' car.id %}" style="text-decoration: none;">
                                <button class="long-button" style="width: 150px;">More details</button>
                            </a>
                        </li>
                    </ul>
                {% endfor %}
            </div>
            {% endif %}

            <!-- Tracks results -->
            {% if tracks %}
            <div class="search-item">
                <h5>Results for "{{ query }}" in Tracks</h5>
                {% for track in tracks %}
                    <ul>
                        <li>
                            <strong>{{ track.name }}</strong>, located in {{ track.location }}
                            {% for image in track.gallery_image_urls %}
                                <a href="{% url 'tracks:details' track.id %}" style="text-decoration: none;">
                                    <img src="{{ image }}" alt="Track details" width="150px">
                                </a>
                            {% endfor %}
                            <a href="{% url 'tracks:details' track.id %}" style="text-decoration: none;">
                                <button class="long-button" style="width: 150px;">More details</button>
                            </a>
                        </li>
                    </ul>
                {% endfor %}
            </div>
            {% endif %}

            <!-- Bookings results -->
            {% if bookings %}
            <div class="search-item">
                <h5>Results for "{{ query }}" in my Bookings</h5>
                {% for booking in bookings %}
                    <ul>
                        <li>
                            {{ booking.booking_number }} - {{ booking.track }} - {{ booking.car }} - {{ booking.date }} - {{ booking.status }}
                            <a href="{% url 'bookings:details' booking.id %}" style="text-decoration: none;">
                                <button class="long-button"  style="width: 150px;">Order details</button>
                            </a>
                        </li>
                    </ul>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
</body>
{% endblock %}